# Generated by Django 3.2.8 on 2021-10-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('parameter', models.CharField(choices=[('generation', 'generation'), ('irradiation', 'irradiation')], max_length=12)),
                ('value', models.DecimalField(decimal_places=5, max_digits=15)),
            ],
        ),
    ]
